### PR TITLE
Improvements on Album Art display

### PR DESCRIPTION
**Pull request by imsamuka**
Re-implemented #54 on the `dev` branch. I'm sorry for not noticing the branch before...
Also:

* Removed the copy-pasted code, and pointed the `gompd` to it's current `master` branch. 
* Complied with the new `cfg.PlayerAlbumArtSize`.
* Created new `cfg.PlayerAlbumArtDynamic` to enable/disable the feature of dynamic sizing.

I don't know if re-doing the PR was the best idea, but i guess that works haha

### CODE REVIEW

**Comment by yktoo** [comment]
Hi @imsamuka, thanks for submitting the pull request.

Could you please elaborate on this bit:
```go
// Down/up-scale the image as needed
var destHeight int

if cfg.PlayerAlbumArtDynamic {
	minHeight := size
	maxHeight := minHeight + 80
	_, windowHeight := w.AppWindow.GetSize()
	destHeight = util.Remap(windowHeight, 460, 660, minHeight, maxHeight)
	destHeight = util.Clamp(destHeight, minHeight, maxHeight)
} else {
	destHeight = size
}
```

I'm struggling to understand the logic here as I don't see any effect from resizing the window or changing the album art dimensions. I'm also in doubt about the hardcoded numbers here.

In general I believe that scaling must always be proportional.

**Comment by imsamuka** [comment]
It means that:
* When `windowHeight <= 460px` the album art height will be `minHeight`
* When `windowHeight >= 660px` the album art height will be `maxHeight`
* When `460px < windowHeight < 660px` the album art height will be in between, linearly proportional:
  * If `windowHeight` is **60%** between `460px` and `660px`, the album art height will be **60%** between `minHeight` and `maxHeight`

## Window height at **460px**:
image


## Window height at **560px**:
image


## Window height at **660px**:
image

I hardcoded the numbers as i saw fitting, regarding the visibility of the play list. Ideally you could add configuration to this numbers and the `+ 80` on the `maxHeight`, but i thought it would be a little too much for the PR.

Unfortunately, i couldn't make the changes dynamic, so the difference is only visible after a music changes, and the album art updates. Notice that the music changed between each print screen.

**Comment by yktoo** [comment]
Okay, after a good deal of deliberation I believe I have a conclusion on this PR.

1. The use of embedded graphics is definitely a very welcome one.
2. The proportional scaling is a must, I should've built that from the beginning (I just didn't consider there might be a non-square image).
3. What you called "dynamic image size" is unfortunately a no-go, at least in its current shape.

To elaborate on the last point:
* The use of hardcoded pixel values feels a bit of a stretch (sorry for the pun). Different themes and DE can have a problem with that.
* As you mentioned, the image size is only updated on a track change. It feels as a sloppy design decision and is confusing for the end user.
* The overall need for "adaptive scaling" is not so high now that the user can configure the image size.
* I don't seem to have seen such a feature elsewhere either.

Going forward, I want to reimplement the first two points outside of this PR and make a new release.

Thanks for your contribution and let's keep in touch!

**Comment by imsamuka** [comment]
I see. No "dynamic" image size is not that much of a loss actually.
@yktoo I will revert the last commit, so you can merge (and close #59) without the "dynamic size" business.

**Comment by yktoo** [comment]
@imsamuka I've already implemented that so no worries!

> No "dynamic" image size is not that much of a loss actually.

Was my thought too :-)

**Pull request closed without merging**
